name: model_viewer_plus
description: "A Flutter widget for rendering interactive 3D models in the glTF and GLB formats"
version: 1.9.2
repository: https://github.com/omchiii/model_viewer_plus.dart
topics:
  - model-viewer
  - model
platforms:
  android:
  ios:
  web:
environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.22.0'

dependencies:
  android_intent_plus: ^5.3.0
  flutter:
    sdk: flutter
  path: ^1.9.1
  url_launcher: ^6.3.1
  web: ^1.1.1
  webview_flutter: ^4.10.0
  webview_flutter_android: ^4.3.4
  webview_flutter_wkwebview: ^3.18.5

dev_dependencies:
  carapacik_lints: ^1.8.1
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/
